formatter: markdown table
header-from: main.tf
sections:
  hide:
  show-all: true

  output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by:
    - required

settings:
  color: true
  escape: true
  indent: 3
  required: false
  sensitive: true